[phases.setup]
nixPkgs = ["python39", "nodejs-20_x", "npm-9_x"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn metis_admin.wsgi:application --bind 0.0.0.0:$PORT"