[phases.setup]
nixPkgs = ['python311', 'pip']
aptPkgs = ['libsqlite3-0', 'libsqlite3-dev', 'sqlite3']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn metis_admin.wsgi:application --bind 0.0.0.0:$PORT'