[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput',
    'python manage.py migrate'
]

[start]
cmd = 'gunicorn metis_admin.wsgi:application --bind 0.0.0.0:$PORT'