[phases.setup]
nixPkgs = ['python311', 'pip', 'bash']
aptPkgs = ['libsqlite3-0', 'libsqlite3-dev', 'sqlite3']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput',
    'chmod +x railway_start.sh'
]

[start]
cmd = 'bash railway_start.sh'