[phases.setup]
nixPkgs = ["python311", "nodejs_20", "npm-10_x"]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade --user",
    "python -m pip install --user -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn metis_admin.wsgi:application -c gunicorn.conf.py"
