from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('analytics/', views.analytics, name='analytics'),
    path('users/', views.users, name='users'),
    path('products/', views.products, name='products'),
    path('finance/', views.finance, name='finance'),
    path('orders/', views.orders, name='orders'),
    path('forms/', views.forms, name='forms'),
    path('elements/', views.elements, name='elements'),
    path('elements/buttons/', views.elements_buttons, name='elements_buttons'),
    path('elements/alerts/', views.elements_alerts, name='elements_alerts'),
    path('elements/badges/', views.elements_badges, name='elements_badges'),
    path('elements/cards/', views.elements_cards, name='elements_cards'),
    path('elements/modals/', views.elements_modals, name='elements_modals'),
    path('elements/forms/', views.elements_forms, name='elements_forms'),
    path('elements/tables/', views.elements_tables, name='elements_tables'),
    path('yeni-lastik/', views.yeni_lastik, name='yeni_lastik'),
    path('siparis/<int:siparis_id>/detay/', views.siparis_detay, name='siparis_detay'),
    path('siparis/<int:siparis_id>/duzenle/', views.siparis_duzenle, name='siparis_duzenle'),
    path('siparis/<int:siparis_id>/sil/', views.siparis_sil, name='siparis_sil'),
    path('siparis/<int:siparis_id>/whatsapp/', views.siparis_whatsapp, name='siparis_whatsapp'),
    path('export-excel/', views.export_excel, name='export_excel'),
    path('export-cancelled-excel/', views.export_cancelled_excel, name='export_cancelled_excel'),
    path('export-checked-excel/', views.export_checked_excel, name='export_checked_excel'),
    path('reports/', views.reports, name='reports'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('messages/', views.messages_view, name='messages'),
    path('calendar/', views.calendar, name='calendar'),
    path('api/events/create/', views.create_event, name='create_event'),
    path('api/events/', views.get_events, name='get_events'),
    path('api/finance/overview/', views.finance_overview, name='finance_overview'),
    # Bildirim API'leri
    path('api/notifications/', views.get_notifications, name='get_notifications'),
    path('api/notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('api/notifications/read-all/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('api/notifications/<int:notification_id>/dismiss/', views.dismiss_notification, name='dismiss_notification'),
    path('kategoriler/', views.kategoriler, name='kategoriler'),
    path('kategoriler/<int:kategori_id>/sil/', views.kategori_sil, name='kategori_sil'),
    path('kategoriler/<int:kategori_id>/duzenle/', views.kategori_duzenle, name='kategori_duzenle'),
    path('api/alt-kategoriler/<int:ana_kategori_id>/', views.get_alt_kategoriler, name='get_alt_kategoriler'),
    path('api/brand-distribution/', views.brand_distribution_api, name='brand_distribution_api'),
    path('settings/', views.settings, name='settings'),
    path('security/', views.security, name='security'),
    path('help/', views.help, name='help'),
    path('malzeme-excel-yukle/', views.malzeme_excel_upload, name='malzeme_excel_upload'),
    path('malzeme-excel-kaydet/', views.malzeme_excel_kaydet, name='malzeme_excel_kaydet'),
    path('health/', views.health_check, name='health_check'),
]
