# Generated by Django 5.2.7 on 2025-10-21 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cari_firma', models.CharField(max_length=200, verbose_name='CARI (FIRMA)')),
                ('marka', models.CharField(max_length=100, verbose_name='MARKA')),
                ('urun', models.CharField(max_length=300, verbose_name='ÜRÜN (LASTIK MARKA MODEL)')),
                ('grup', models.CharField(choices=[('ticari', 'Ticari'), ('binek', 'Binek'), ('aku', 'Akü'), ('jant', 'Jant')], max_length=20, verbose_name='GRUP')),
                ('mevsim', models.CharField(choices=[('kis', 'Kış'), ('yaz', 'Yaz'), ('dort-mevsim', '4 Mevsim')], max_length=20, verbose_name='MEVSİM')),
                ('adet', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ADET')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='BİRİM FİYAT')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TOPLAM FİYAT')),
                ('durum', models.CharField(choices=[('yolda', 'Yolda'), ('stok', 'Stok'), ('teslim', 'Teslim'), ('beklemede', 'Beklemede'), ('iptal', 'İptal')], default='yolda', max_length=20, verbose_name='DURUM')),
                ('ambar', models.CharField(default='Stok', max_length=100, verbose_name='AMBAR')),
                ('odeme', models.CharField(choices=[('nakit', 'NAKİT'), ('havale', 'HAVALE'), ('kredi-karti', 'KREDİ KARTI'), ('cek', 'ÇEK')], max_length=20, verbose_name='ÖDEME')),
                ('sms_durum', models.CharField(choices=[('gonderildi', 'Gönderildi'), ('beklemede', 'Beklemede'), ('gonderilmedi', 'Gönderilmedi')], default='beklemede', max_length=20, verbose_name='SMS')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='AÇIKLAMA')),
                ('one_cikar', models.BooleanField(default=False, verbose_name='ÖNE ÇIKAR')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
