# Generated by Django 5.2.7 on 2025-10-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='ambar',
            field=models.CharField(choices=[('stok', 'Stok'), ('depo', 'Depo'), ('satis', 'Satış'), ('uretim', 'Üretim'), ('kalite', 'Kalite')], default='stok', max_length=20, verbose_name='AMBAR'),
        ),
    ]
