# Generated by Django 5.2.7 on 2025-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_siparis_ambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='ambar',
            field=models.CharField(choices=[('stok', 'Stok'), ('satis', 'Satış')], default='stok', max_length=20, verbose_name='AMBAR'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='odeme',
            field=models.CharField(choices=[('kredi-karti', 'Kredi Kartı'), ('havale', 'Havale'), ('cari-hesap', 'Cari Hesap')], max_length=20, verbose_name='ÖDEME'),
        ),
    ]
