# Generated by Django 5.2.7 on 2025-10-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_siparis_ambar_alter_siparis_odeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='sms_durum',
            field=models.CharField(choices=[('gonderilmedi', 'Gönderilmedi'), ('gonderildi', 'Gönderildi')], default='gonderilmedi', max_length=20, verbose_name='SMS'),
        ),
    ]
