# Generated by Django 5.2.7 on 2025-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_siparis_sms_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('yolda', 'Yolda'), ('islemde', 'İşleme Devam Ediyor'), ('teslim', 'Teslim Edildi'), ('kontrol', 'Kontrol Edildi'), ('iptal', 'İptal Edildi')], default='yolda', max_length=20, verbose_name='DURUM'),
        ),
    ]
