# Generated by Django 5.1.4 on 2025-10-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_siparis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='iptal_sebebi',
            field=models.TextField(blank=True, null=True, verbose_name='İPTAL SEBEBİ'),
        ),
    ]
