# Generated by Django 5.1.4 on 2025-10-27 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_siparis_iptal_sebebi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('type', models.CharField(choices=[('event_reminder', 'Etkinlik Hatırlatıcısı'), ('event_start', 'Etkinlik Başlangıcı'), ('system', 'Sistem Bildirimi'), ('info', 'Bilgi'), ('warning', 'Uyarı'), ('error', 'Hata')], default='info', max_length=20, verbose_name='Tür')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('sent', 'Gönderildi'), ('read', 'Okundu'), ('dismissed', 'Kapatıldı')], default='pending', max_length=20, verbose_name='Durum')),
                ('scheduled_time', models.DateTimeField(verbose_name='Planlanmış Zaman')),
                ('sent_time', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Zamanı')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Zamanı')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='Ek Veriler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.event', verbose_name='İlişkili Etkinlik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
