# Generated by Django 5.2.7 on 2025-10-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_transactioncategory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hareket_tipi',
            field=models.CharField(choices=[('gelir', 'Gelir'), ('gider', 'Gider')], default='gelir', max_length=10, verbose_name='Hareket Tipi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kasa_adi',
            field=models.CharField(choices=[('merkez-satis', 'Merkez Satış'), ('servis', 'Servis')], default='merkez-satis', max_length=20, verbose_name='Kasa Adı'),
        ),
    ]
