# Generated by Django 5.2.7 on 2025-10-28 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_transaction_hareket_tipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mehmet_havale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mehmet Havale'),
        ),
    ]
