# Generated by Django 5.1.4 on 2025-10-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_transactioncategory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
    ]
