# Generated by Django 5.1.4 on 2025-10-29 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_notification_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('type', models.CharField(choices=[('event', 'Etkinlik'), ('meeting', 'Toplantı'), ('task', 'Görev'), ('reminder', 'Hatırlatıcı'), ('deadline', 'Son Tarih')], default='event', max_length=20, verbose_name='Tür')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=20, verbose_name='Öncelik')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Süre (dakika)')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Konum')),
                ('attendees', models.TextField(blank=True, null=True, verbose_name='Katılımcılar')),
                ('recurring', models.BooleanField(default=False, verbose_name='Tekrarlanan')),
                ('recurrence', models.CharField(choices=[('none', 'Tekrarlanmaz'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('biweekly', '2 Haftada Bir'), ('monthly', 'Aylık'), ('yearly', 'Yıllık')], default='none', max_length=20, verbose_name='Tekrar Deseni')),
                ('reminders', models.TextField(blank=True, null=True, verbose_name='Hatırlatıcılar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['date', 'time'],
            },
        ),
    ]
