# Generated by Django 5.1.4 on 2025-10-30 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_railway_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MalzemeHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('faturano', models.CharField(max_length=100)),
                ('musteri', models.CharField(max_length=255)),
                ('urun', models.CharField(max_length=255)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('odeme_sekli', models.CharField(max_length=100)),
                ('eklenme_zamani', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
