# Generated by Django 5.1.4 on 2025-10-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_malzemehareketi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MalzemeDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya_adi', models.CharField(max_length=200)),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='malzemehareketi',
            name='dosya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='dashboard.malzemedosya'),
        ),
    ]
